"""empty message

Revision ID: 0bdbfb44c1a1
Revises: 97b15b464d99
Create Date: 2020-12-02 23:59:15.764999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bdbfb44c1a1'
down_revision = '97b15b464d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sinnoh_pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('dex_id', sa.Integer(), nullable=True),
    sa.Column('type1', sa.String(length=20), nullable=True),
    sa.Column('type2', sa.String(length=20), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('sprite', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sinnoh_pokemon')
    # ### end Alembic commands ###
