"""empty message

Revision ID: 9c4462a40fbf
Revises: 0bdbfb44c1a1
Create Date: 2020-12-03 00:05:08.834042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c4462a40fbf'
down_revision = '0bdbfb44c1a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alola_pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('dex_id', sa.Integer(), nullable=True),
    sa.Column('type1', sa.String(length=20), nullable=True),
    sa.Column('type2', sa.String(length=20), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('sprite', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alola_pokemon')
    # ### end Alembic commands ###
