"""empty message

Revision ID: 2fe8b2922b6b
Revises: 89a842c54dec
Create Date: 2020-12-02 22:57:52.325875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe8b2922b6b'
down_revision = '89a842c54dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('national_pokemon', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('national_pokemon', 'price')
    # ### end Alembic commands ###
