"""empty message

Revision ID: 333fb1a21bfe
Revises: 
Create Date: 2020-12-02 21:59:15.025251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333fb1a21bfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('national_pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('dex_id', sa.Integer(), nullable=True),
    sa.Column('type1', sa.String(length=20), nullable=True),
    sa.Column('type2', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('sprite', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('national_pokemon')
    # ### end Alembic commands ###
