"""empty message

Revision ID: 4b471bbc0004
Revises: 333fb1a21bfe
Create Date: 2020-12-02 22:21:26.274989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b471bbc0004'
down_revision = '333fb1a21bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('national_pokemon', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('national_pokemon', 'price')
    # ### end Alembic commands ###
