"""empty message

Revision ID: 4ea9e23cc5e5
Revises: 2fe8b2922b6b
Create Date: 2020-12-02 23:36:32.129935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea9e23cc5e5'
down_revision = '2fe8b2922b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('johto_pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('dex_id', sa.Integer(), nullable=True),
    sa.Column('type1', sa.String(length=20), nullable=True),
    sa.Column('type2', sa.String(length=20), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('sprite', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('johto_pokemon')
    # ### end Alembic commands ###
