"""empty message

Revision ID: 506ccf65e57f
Revises: e15cf0422a18
Create Date: 2020-12-03 00:22:51.875464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506ccf65e57f'
down_revision = 'e15cf0422a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('weak', sa.String(length=100), nullable=True),
    sa.Column('strong', sa.String(length=100), nullable=True),
    sa.Column('immune', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_types')
    # ### end Alembic commands ###
