"""empty message

Revision ID: 89a842c54dec
Revises: e956985ff509
Create Date: 2020-12-02 22:57:33.513431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a842c54dec'
down_revision = 'e956985ff509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('national_pokemon', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('national_pokemon', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
