"""empty message

Revision ID: e956985ff509
Revises: 4b471bbc0004
Create Date: 2020-12-02 22:47:08.536332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e956985ff509'
down_revision = '4b471bbc0004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('national_pokemon', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('national_pokemon', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
